name: CI/CD Pipeline
on:
  push:
    branches: [main]
env:
  ACR_REGISTRY: monprojetdevops.azurecr.io
  IMAGE_NAME: mon-app

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      # Stage 1 - Checkout
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "SHA = ${{ github.sha }}"

      # Stage 2 - Lint
      - name: Lint
        run: |
          pip install flake8
          flake8 app/ --max-line-length=100

      # Stage 3 - Build & Test
      - name: Build & Test
        run: |
          pip install -r requirements.txt
          pytest tests/ --cov=app --cov-report=xml

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml

      # Stage 4 - SonarQube
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Stage 5 - Quality Gate
      - name: Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Stage 6 - Security Scan Trivy
      - name: Build Docker image (pour Trivy)
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
          format: table
          exit-code: 0

      # Stage 7 - Push to ACR
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push image
        run: |
          docker tag $IMAGE_NAME:${{ github.sha }} $ACR_REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker tag $IMAGE_NAME:${{ github.sha }} $ACR_REGISTRY/$IMAGE_NAME:latest
          docker push $ACR_REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $ACR_REGISTRY/$IMAGE_NAME:latest

      # Stage 8 - IaC Apply (Terraform)
      # Stage 8 - IaC Apply (manuel - Azure AD restreint sur tenant universitaire)
      - name: "⑧ Terraform Info"
        run: |
          echo "Terraform apply exécuté manuellement depuis Azure Cloud Shell"
          echo "App URL: https://mon-app-staging-jihane.azurewebsites.net"
          echo "Région: Spain Central"
          echo "Resource Group: rg-staging"
      # Stage 8 - IaC Apply (manuel - Azure AD restreint sur tenant universitaire)
      - name: "⑧ Terraform Info"
        run: |
          echo "Terraform apply exécuté manuellement depuis Azure Cloud Shell"
          echo "App URL: https://mon-app-staging-jihane.azurewebsites.net"
          echo "Région: Spain Central"
          echo "Resource Group: rg-staging"

     # Stage 9 - Smoke Test
      - name: Smoke Test
        run: |
          APP_URL="https://mon-app-staging-jihane.azurewebsites.net"
          sleep 15
          curl -f "$APP_URL/health"
